geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),

]

geekshop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp


app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import main, contacts
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name='main'),
    path('contacts/', contacts, name='contacts'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from .views import products


app_name = 'mainapp'

urlpatterns = [
    path('', products, name='main'),
    path('category/<int:pk>', products, name='category'),
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(
        max_length=64,
        verbose_name='Имя',
        unique=True,
    )

    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )

    created = models.DateTimeField(
        auto_now_add=True
    )

    updated = models.DateTimeField(
        auto_now=True
    )

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE
    )

    name = models.CharField(
        verbose_name='Имя продукта',
        max_length=128,
    )

    image = models.ImageField(
        upload_to='products_images',
        blank=True
    )

    short_desc = models.CharField(
        verbose_name='краткое описание',
        max_length=5,
        blank=True
    )

    description = models.TextField(
        verbose_name='описание продукта',
        blank=True
    )
    created = models.DateTimeField(
        auto_now_add=True
    )

    updated = models.DateTimeField(
        auto_now=True
    )
    price = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        verbose_name='цена'
    )

    quantity = models.PositiveIntegerField(
        verbose_name='количество на складе',
        default=0
    )

    def __str__(self):
        return f"{self.name}, ({self.category.name})"


    class Meta:
        ordering=['created']
        verbose_name = 'товар'
        verbose_name_plural = 'товары'

geekshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404

from basketapp.models import Basket
from mainapp.models import ProductCategory, Product


def products(request, pk=None):
    title = 'Каталог'
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
    links_menu = ProductCategory.objects.all()
    products = Product.objects.all().order_by('price')

    if pk is not None:
        if pk ==0:
            products = Product.objects.all().order_by('price')
            category = {'name': 'все'}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by('price')

        context = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products,
            'basket': basket,

        }
        return render(request, 'mainapp/products.html', context=context)
    same_products = Product.objects.all()[1:2]
    context = {
        'title': title,
        'links_menu': links_menu,
        'same_products': same_products,
        'products': products,
        'basket': basket,

    }

    return render(request, 'mainapp/products.html', context=context)

geekshop/mainapp/templates/mainapp/products.html
{% extends 'geekshop/base.html' %}
{% load static %}

{% block css %}
	<link rel="stylesheet" type="text/css" href="{% static 'mainapp/style.css' %}">
	<link rel="stylesheet" href="{% static 'mainapp/fonts/font-awesome/css/font-awesome.css' %}">
{% endblock %}
{% block content %}
		<div class="hero-white">
			<div class="header clearfix">
				<a href="{% url 'main' %}" class="logo"></a>
				<ul class="menu">
					<li><a href="{% url 'main' %}">домой</a></li>
					<li><a href="{% url 'products:main' %}" class="active">продукты</a></li>
					{% if user.is_authenticated %}
					<li>
   						 	<a href="{% url 'auth:edit' %}">
        						{{ user.first_name|default:'Пользователь' }}
							</a>
					</li>
					{% if basket %}
					<li><a href="{% url 'basket:view' %}">Корзина</a>
					 <span>
							({{ basket|length }} шт.)
					 </span>
					</li>
					{% endif %}
					{% endif %}
					<li>
						{% if user.is_authenticated %}
						  <a href="{% url 'auth:logout' %}">выйти</a>
						{% else %}
						  <a href="{% url 'auth:login' %}">войти</a>
						{% endif %}
					</li>

					<li><a href="{% url 'contacts' %}">контакты</a></li>

				</ul>
				<a href="#" class="search"></a>
                <a href="#" class="basket"></a>
			</div>
		</div>

		<div class="details">
			<div class="links clearfix">
				<ul class="links-menu">
					<li>
						<a href="{% url 'products:category' 0 %}" class="
					{% if request.resolver_match.kwargs.pk == 0 %}
                        active
                    {% endif %}">Все</a></li>
					{% for link in links_menu %}
					<li><a href="{% url 'products:category' link.pk %}" class="
					{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}
                        active
                    {% endif %}">{{link.name}}</a></li>
					{% endfor %}

				</ul>
			</div>

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="{% static 'mainapp/img/slider1.jpg' %}">
					</div>
					<div class="slider-control">
						<div class="block">
							<a href="#"><img src="{% static 'mainapp/img/controll.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static 'mainapp/img/controll1.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static 'mainapp/img/controll2.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">Отличный стул</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price"> 2585.9 <span>руб</span></p>
					<a href="#" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						<p>Расположитесь комфортно.</p> 
						<p>Отличное качество материалов
						позволит вам это.</p> 
						<p>Различные цвета</p>
						<p>высочайший уровень
						эргономики и прочность.</p>
					</div>
				</div>
			</div>
			<div class="products_list">
      			<div class="title clearfix">
					{% if category %}
        				<h2>
          					Категория: "{{ category.name|title }}"
       			 		</h2>
					{% endif %}
      			</div>
      			<div class="category-products clearfix">

					{% for product in products %}
					<div class="block">
            			<a href="{%url 'basket:add' product.pk%}">
							<img src="/media/{{ product.image }}" alt="product">
							<div class="text">
                				<img src="{% static 'img/icon-hover.png' %}" alt="hover">
                  				<h4>{{ product.name }}</h4>
                  				<p>{{ product.description }}</p>
							</div>
            			</a>
         	 		</div>
        			{% endfor %}

      </div>


			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="{% static 'mainapp/img/arrow.png' %}" alt=""></a>
				</div>
				<div class="related-products clearfix">
					{% for same_product in same_products %}
						<div class="block">
						<a href="#"><img src="{% static 'mainapp/img/product-11.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'mainapp/img/icon-hover.png' %}" alt="img">
								<h4>{{same_product.name}}</h4>
								<p>{{same_product.description}} </p>
							</div>
						</a>
					</div>
					{% endfor %}

				</div>
			</div>
		</div>

{% endblock %}